source [find interface/imx-native.cfg]
transport select swd
source [find target/nrf52.cfg]

imx_gpio_peripheral_base 0x30230000
imx_gpio_swd_nums 12 13

init
targets
reset halt
nrf5 mass_erase
program radio_test_heimdall_boardv2.hex verify

reset run
exit
